### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by mocherry23** [BiaPyX/BiaPy#105]
Dear all,

I tried to install Biapy on a Windows 10 system. Docker is running and during installation there were no errors. However, when I start the GUI, I get the following error window:
![image](https://github.com/user-attachments/assets/e5bcbeb2-0b76-4cdb-9fae-dd6c3e4e1cf9)

Any suggestions?
Thanks and best,
Matthias

**Comment by danifranco** [comment]
This is the same problem as in https://github.com/BiaPyX/BiaPy-GUI/issues/11. As I answered there, this problem has been solved in the upcoming BiaPy-GUI release (specifically in was solved here due to the error reported here: https://github.com/BiaPyX/BiaPy-GUI/issues/10) . I'm closing this to only have one issue and will write you there once the new version is released in the following days. Thanks!!
