### ISSUE TITLE
Input zarr axes order in config file while loading Zarr/H5

### ISSUE THREAD

**Issue by ClementCaporal** [BiaPyX/BiaPy#43]
Hello!

Thank you for your work

## Pitch

I would like to load in BiaPy any zarr format without having to respect the current specific order (z, y, x, c).
I think for example that many zarr will respect the ome-zarr convention (t, z, c, y, x)

It could be a variable in the config file

**Comment by danifranco** [comment]
Hi!

Just added `TEST.BY_CHUNKS.INPUT_IMG_AXES_ORDER` variable in [this commit](https://github.com/danifranco/BiaPy/commit/c6cc49d8e728d9c1d1f30f57e23ea698eeca4316) so you can control it as suggested. Now four different types of axis orders are supported `['TZCYX', 'TZYXC', 'ZCYX', 'ZYXC']`. The default behaviour is to expect `'TZCYX'` order as ome-zarr. 

Hope you find it useful. Let me know if you find any issue! :D

**Comment by ClementCaporal** [comment]
Hello @danifranco.
Thank you very much for your work.

I have several small questions:
- Is there a reason to support only these axis order? (`['TZCYX', 'TZYXC', 'ZCYX', 'ZYXC']`). If not I propose this pull request for a versatile TEST.BY_CHUNKS.INPUT_IMG_AXES_ORDER : #45 . The main idea is to sort the axis on the fly using a new `util.order_dimensions()` function.
- [This lines](https://github.com/ClementCaporal/BiaPy/blob/6aa291baa9bc5d7fb410454bfcea3a3da0c23604/biapy/engine/base_workflow.py#L848-L852) suggest that T is always first? Is there a specific utility to add it to the `data_shape` ?

**Comment by danifranco** [comment]
Hello!

- There was not specific motivation to only support 4 axis order. The function and rest of the changes added in your PR are awesome. Thanks a lot!
- I decided to make the T always first and include it even if the user didn't select it just to have a consistent output, nothing more behind... I'm open to any suggestions. In [insert_patch_into_dataset()](https://github.com/ClementCaporal/BiaPy/blob/6aa291baa9bc5d7fb410454bfcea3a3da0c23604/biapy/engine/base_workflow.py#L1578) the part that each GPU processes is created. Then, the [main process](https://github.com/ClementCaporal/BiaPy/blob/6aa291baa9bc5d7fb410454bfcea3a3da0c23604/biapy/engine/base_workflow.py#L941) is in charge of merging those pieces into the final large Zarr [here](https://github.com/ClementCaporal/BiaPy/blob/6aa291baa9bc5d7fb410454bfcea3a3da0c23604/biapy/engine/base_workflow.py#L981) or [here](https://github.com/ClementCaporal/BiaPy/blob/6aa291baa9bc5d7fb410454bfcea3a3da0c23604/biapy/engine/base_workflow.py#L1013). So, maybe we can apply the same procedure to have an output as the user's input axis order. I'm not very used to work with Zarr files but it could be interesting, no? What you do think? If so, do you want to make the changes? So everything could support versatile axis order. 

Another thing, could you please only commit the changes in those lines that you really change something? I mean, now there are a lot of additions/removals because of blank spaces and it's hard to see sometimes what's new was added. 

Again, thanks a lot for the changes Clement!!
